### ISSUE TITLE
Gallery inside the form view ?

### ISSUE THREAD

**Issue by kaizokou** [funcphp/EasyAdminGalleryBundle#1]
Hello @emr 
Is it possible to add a gallery inside the form view ?

Ex : 

```
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'gallery', type: 'easy_admin_gallery'}

```

Thx.
